name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: checkout repo
        uses: actions/checkout@v4
      - name: insatll wgvet
        run: go install github.com/sean9999/wgvet@latest
      - name: vet
        run: wgvet ./...
